# Generated by Django 3.2 on 2023-06-02 16:12

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_cooking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='recipes.RecipeIngredients', to='recipes.Ingredient', validators=[api.validators.validate_ingredients], verbose_name='Ингридиенты'),
        ),
    ]
